{"version": 2, "width": 230, "height": 55, "timestamp": 1661457091, "env": {"SHELL": "/bin/bash", "TERM": "xterm-256color"}, "title": "Almalinux9 on OCI with Ampere A1 and Terraform"}
[0.394234, "o", "hostkeys_find_by_key_hostfile: hostkeys_foreach failed for /etc/ssh/ssh_known_hosts: Permission denied\r\r\n\rThe authenticity of host '155.248.229.159 (155.248.229.159)' can't be established.\r\nED25519 key fingerprint is SHA256:e1mcOQcEUnP0xy/IRKuqjuxYghz/E4Z4sHZypQBISQY.\r\nThis key is not known by any other names\r\nAre you sure you want to continue connecting (yes/no/[fingerprint])? "]
[1.800215, "o", "y"]
[1.853801, "o", "e"]
[1.97572, "o", "s"]
[2.451558, "o", "\r\n"]
[2.453147, "o", "Warning: Permanently added '155.248.229.159' (ED25519) to the list of known hosts.\r\r\n"]
[3.881407, "o", "\u001b]0;opc@ampere-a1-almalinux-9-01:~\u0007\u001b[?2004h[opc@ampere-a1-almalinux-9-01 ~]$ "]
[4.714216, "o", "s"]
[4.810021, "o", "u"]
[4.918351, "o", "d"]
[4.989918, "o", "o"]
[5.106273, "o", " "]
[5.278003, "o", "c"]
[5.434242, "o", "a"]
[5.5464, "o", "t"]
[5.67793, "o", " "]
[5.802354, "o", "/"]
[5.905865, "o", "e"]
[5.965886, "o", "t"]
[6.154161, "o", "c"]
[6.270051, "o", "/"]
[6.834356, "o", "r"]
[6.950329, "o", "e"]
[7.134274, "o", "d"]
[7.586097, "o", "h"]
[7.701988, "o", "a"]
[7.758337, "o", "t"]
[8.218105, "o", "-"]
[8.434295, "o", "r"]
[8.518008, "o", "e"]
[8.662706, "o", "l"]
[8.746258, "o", "e"]
[8.909899, "o", "a"]
[9.110047, "o", "s"]
[9.186088, "o", "e"]
[9.826086, "o", "\r\n\u001b[?2004l\r"]
[9.870507, "o", "AlmaLinux release 9.0 (Emerald Puma)\r\n"]
[9.872696, "o", "\u001b]0;opc@ampere-a1-almalinux-9-01:~\u0007\u001b[?2004h[opc@ampere-a1-almalinux-9-01 ~]$ "]
[10.65027, "o", "s"]
[10.766281, "o", "u"]
[10.862127, "o", "d"]
[10.945998, "o", "o"]
[11.062277, "o", " "]
[11.554137, "o", "c"]
[11.682369, "o", "a"]
[11.782316, "o", "t"]
[12.770409, "o", " "]
[12.970365, "o", "/"]
[13.298396, "o", "v"]
[13.417929, "o", "a"]
[13.4983, "o", "r"]
[13.666009, "o", "/"]
[13.902303, "o", "l"]
[14.146095, "o", "o"]
[14.218029, "o", "g"]
[14.722297, "o", "/"]
[14.902299, "o", "c"]
[15.014103, "o", "l"]
[15.218152, "o", "o"]
[15.390175, "o", "u"]
[15.550216, "o", "d"]
[15.986138, "o", "-"]
[16.294161, "o", "i"]
[16.361957, "o", "n"]
[16.534262, "o", "i"]
[16.634017, "o", "t"]
[16.814538, "o", "."]
[17.614776, "o", "log "]
[19.074304, "o", "\r\n\u001b[?2004l\r"]
[19.103616, "o", "2022-08-25 19:51:12,124 - util.py[DEBUG]: Cloud-init v. 21.1-19.el9.alma running 'init-local' at Thu, 25 Aug 2022 19:51:12 +0000. Up 12.89 seconds.\r\n2022-08-25 19:51:12,124 - main.py[DEBUG]: No kernel command line url found.\r\n2022-08-25 19:51:12,124 - main.py[DEBUG]: Closing stdin.\r\n2022-08-25 19:51:12,125 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=False)\r\n2022-08-25 19:51:12,127 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)\r\n2022-08-25 19:51:12,133 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=False)\r\n2022-08-25 19:51:12,135 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)\r\n2022-08-25 19:51:12,139 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-instance (recursive=False)\r\n2022-08-25 19:51:12,140 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)\r\n2022-08-25 19:51:12,146 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cl"]
[19.105762, "o", "oud/scripts/per-once (recursive=False)\r\n2022-08-25 19:51:12,148 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)\r\n2022-08-25 19:51:12,155 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-boot (recursive=False)\r\n2022-08-25 19:51:12,157 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)\r\n2022-08-25 19:51:12,166 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/vendor (recursive=False)\r\n2022-08-25 19:51:12,167 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)\r\n2022-08-25 19:51:12,180 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/seed (recursive=False)\r\n2022-08-25 19:51:12,180 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)\r\n2022-08-25 19:51:12,193 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances (recursive=False)\r\n2022-08-25 19:51:12,193 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)\r"]
[19.107549, "o", "\n2022-08-25 19:51:12,203 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/handlers (recursive=False)\r\n2022-08-25 19:51:12,203 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)\r\n2022-08-25 19:51:12,213 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/sem (recursive=False)\r\n2022-08-25 19:51:12,214 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data (recursive=False)\r\n2022-08-25 19:51:12,214 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes\r\n2022-08-25 19:51:12,216 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)\r\n2022-08-25 19:51:12,216 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)\r\n2022-08-25 19:51:12,216 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished\r\n2022-08-25 19:51:12,216 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/data/no-net\r\n2022-08-25 19:51:12,217 - handlers.py[DEBUG]: start: init-local/check-cache: at"]
[19.108443, "o", "tempting to read from cache [check]\r\n2022-08-25 19:51:12,217 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)\r\n2022-08-25 19:51:12,217 - stages.py[DEBUG]: no cache found\r\n2022-08-25 19:51:12,217 - handlers.py[DEBUG]: finish: init-local/check-cache: SUCCESS: no cache found\r\n2022-08-25 19:51:12,217 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance\r\n2022-08-25 19:51:12,222 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.rhel.Distro'>\r\n2022-08-25 19:51:12,222 - __init__.py[DEBUG]: Looking for data source in: ['Oracle', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM']\r\n2022-08-25 19:51:12,236 - __init__.py[DEBUG]: Searching for local data source in: ['DataSourceOracle']\r\n2022-08-25 19:51:12,236 - handlers.py[DEBUG]: start: init-local/search-Oracle: searching for local data from DataSourceOracle\r\n2022-08-25 19:51:12,236 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceOracle."]
[19.109219, "o", "DataSourceOracle'>\r\n2022-08-25 19:51:12,237 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot\r\n2022-08-25 19:51:12,237 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag\r\n2022-08-25 19:51:12,237 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_uuid\r\n2022-08-25 19:51:12,238 - util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)\r\n2022-08-25 19:51:12,238 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address\r\n2022-08-25 19:51:12,238 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)\r\n2022-08-25 19:51:12,238 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address\r\n2022-08-25 19:51:12,238 - __init__.py[DEBUG]: Stable ifnames disabled by net.ifnames=0 in /proc/cmdline\r\n2022-08-25 19:51:12,238 - util.py[DEBUG]: Reading from /sys/class/net/eth0/carrier (quiet=False)\r\n2022-08-25 19:51:12,238 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/carrier\r\n2022-08-25 19:51:12,2"]
[19.109911, "o", "38 - util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)\r\n2022-08-25 19:51:12,238 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address\r\n2022-08-25 19:51:12,240 - dhcp.py[DEBUG]: Performing a dhcp discovery on eth0\r\n2022-08-25 19:51:12,240 - util.py[DEBUG]: Copying /usr/sbin/dhclient to /var/tmp/cloud-init/cloud-init-dhcp-o_gcbbnh/dhclient\r\n2022-08-25 19:51:12,246 - subp.py[DEBUG]: Running command ['ip', 'link', 'set', 'dev', 'eth0', 'up'] with allowed return codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:12,264 - subp.py[DEBUG]: Running command ['/var/tmp/cloud-init/cloud-init-dhcp-o_gcbbnh/dhclient', '-1', '-v', '-lf', '/var/tmp/cloud-init/cloud-init-dhcp-o_gcbbnh/dhcp.leases', '-pf', '/var/tmp/cloud-init/cloud-init-dhcp-o_gcbbnh/dhclient.pid', 'eth0', '-sf', '/bin/true'] with allowed return codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:12,379 - util.py[DEBUG]: All files appeared after 0 seconds: ['/var/tmp/cloud-init/cloud-init-dhcp-o_gcbbnh/dhclient.pid', '"]
[19.110935, "o", "/var/tmp/cloud-init/cloud-init-dhcp-o_gcbbnh/dhcp.leases']\r\n2022-08-25 19:51:12,379 - util.py[DEBUG]: Reading from /var/tmp/cloud-init/cloud-init-dhcp-o_gcbbnh/dhclient.pid (quiet=False)\r\n2022-08-25 19:51:12,380 - util.py[DEBUG]: Read 0 bytes from /var/tmp/cloud-init/cloud-init-dhcp-o_gcbbnh/dhclient.pid\r\n2022-08-25 19:51:12,391 - util.py[DEBUG]: Reading from /var/tmp/cloud-init/cloud-init-dhcp-o_gcbbnh/dhclient.pid (quiet=False)\r\n2022-08-25 19:51:12,391 - util.py[DEBUG]: Read 4 bytes from /var/tmp/cloud-init/cloud-init-dhcp-o_gcbbnh/dhclient.pid\r\n2022-08-25 19:51:12,391 - util.py[DEBUG]: Reading from /proc/958/stat (quiet=True)\r\n2022-08-25 19:51:12,391 - util.py[DEBUG]: Read 305 bytes from /proc/958/stat\r\n2022-08-25 19:51:12,391 - dhcp.py[DEBUG]: killing dhclient with pid=958\r\n2022-08-25 19:51:12,392 - util.py[DEBUG]: Reading from /var/tmp/cloud-init/cloud-init-dhcp-o_gcbbnh/dhcp.leases (quiet=False)\r\n2022-08-25 19:51:12,392 - util.py[DEBUG]: Read 514 bytes from /var/tmp/cloud-init/cloud-init-dhcp-o_gcbbnh/d"]
[19.112083, "o", "hcp.leases\r\n2022-08-25 19:51:12,393 - dhcp.py[DEBUG]: Received dhcp lease on eth0 for 10.2.1.185/255.255.255.0\r\n2022-08-25 19:51:12,393 - __init__.py[DEBUG]: Attempting setup of ephemeral network on eth0 with 10.2.1.185/24 brd 10.2.1.255\r\n2022-08-25 19:51:12,394 - subp.py[DEBUG]: Running command ['ip', '-family', 'inet', 'addr', 'add', '10.2.1.185/24', 'broadcast', '10.2.1.255', 'dev', 'eth0'] with allowed return codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:12,398 - __init__.py[DEBUG]: Skip ephemeral network setup, eth0 already has address 10.2.1.185\r\n2022-08-25 19:51:12,398 - subp.py[DEBUG]: Running command ['ip', '-4', 'route', 'append', '0.0.0.0/0', 'via', '10.2.1.1', 'dev', 'eth0'] with allowed return codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:12,401 - subp.py[DEBUG]: Running command ['ip', '-4', 'route', 'append', '169.254.0.0/16', 'via', '0.0.0.0', 'dev', 'eth0'] with allowed return codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:12,404 - url_helper.py[DEBUG]: [0/3] open "]
[19.112801, "o", "'http://169.254.169.254/opc/v2/instance/' with {'url': 'http://169.254.169.254/opc/v2/instance/', 'allow_redirects': True, 'method': 'GET', 'headers': {'User-Agent': 'Cloud-Init/21.1-19.el9.alma', 'Authorization': 'Bearer Oracle'}} configuration\r\n2022-08-25 19:51:12,412 - url_helper.py[DEBUG]: Read from http://169.254.169.254/opc/v2/instance/ (200, 3795b) after 1 attempts\r\n2022-08-25 19:51:12,413 - subp.py[DEBUG]: Running command ['ip', '-4', 'route', 'del', '169.254.0.0/16', 'via', '0.0.0.0', 'dev', 'eth0'] with allowed return codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:12,415 - subp.py[DEBUG]: Running command ['ip', '-4', 'route', 'del', '0.0.0.0/0', 'via', '10.2.1.1', 'dev', 'eth0'] with allowed return codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:12,420 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmpy3u7k1ej) - w: [600] 9353 bytes/chars\r\n2022-08-25 19:51:12,420 - atomic_helper.py[DEBUG]: Atomic"]
[19.113611, "o", "ally writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmpto8nuz7f) - w: [644] 6118 bytes/chars\r\n2022-08-25 19:51:12,421 - handlers.py[DEBUG]: finish: init-local/search-Oracle: SUCCESS: found local data from DataSourceOracle\r\n2022-08-25 19:51:12,421 - stages.py[INFO]: Loaded datasource DataSourceOracle - DataSourceOracle\r\n2022-08-25 19:51:12,421 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)\r\n2022-08-25 19:51:12,421 - util.py[DEBUG]: Read 1274 bytes from /etc/cloud/cloud.cfg\r\n2022-08-25 19:51:12,421 - util.py[DEBUG]: Attempting to load yaml from string of length 1274 with allowed root types (<class 'dict'>,)\r\n2022-08-25 19:51:12,426 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)\r\n2022-08-25 19:51:12,427 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg\r\n2022-08-25 19:51:12,427 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)\r\n2022-"]
[19.114512, "o", "08-25 19:51:12,429 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)\r\n2022-08-25 19:51:12,430 - util.py[DEBUG]: Read 34 bytes from /run/cloud-init/cloud.cfg\r\n2022-08-25 19:51:12,430 - util.py[DEBUG]: Attempting to load yaml from string of length 34 with allowed root types (<class 'dict'>,)\r\n2022-08-25 19:51:12,430 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)\r\n2022-08-25 19:51:12,430 - util.py[DEBUG]: loaded blob returned None, returning default.\r\n2022-08-25 19:51:12,430 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance\r\n2022-08-25 19:51:12,430 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a'\r\n2022-08-25 19:51:12,431 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg"]
[19.1155, "o", "2s6pl6a (recursive=True)\r\n2022-08-25 19:51:12,436 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/handlers (recursive=False)\r\n2022-08-25 19:51:12,437 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a (recursive=True)\r\n2022-08-25 19:51:12,441 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/scripts (recursive=False)\r\n2022-08-25 19:51:12,442 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a (recursive=True)\r\n2022-08-25 19:51:12,448 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2"]
[19.134716, "o", "almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem (recursive=False)\r\n2022-08-25 19:51:12,449 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/datasource (quiet=False)\r\n2022-08-25 19:51:12,449 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/datasource - wb: [644] 35 bytes\r\n2022-08-25 19:51:12,449 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/datasource (recursive=False)\r\n2022-08-25 19:51:12,450 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/datasource (recursive=False)\r\n2022-08-25 19:51:12,451 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 35 bytes\r\n2022-08-2"]
[19.135896, "o", "5 19:51:12,451 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)\r\n2022-08-25 19:51:12,452 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)\r\n2022-08-25 19:51:12,452 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)\r\n2022-08-25 19:51:12,452 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID\r\n2022-08-25 19:51:12,452 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 94 bytes\r\n2022-08-25 19:51:12,453 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)\r\n2022-08-25 19:51:12,453 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)\r\n2022-08-25 19:51:12,454 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 94 bytes\r\n2022-08-25 19:51:12,454 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)\r\n2022-08-25 19"]
[19.136653, "o", ":51:12,454 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)\r\n2022-08-25 19:51:12,454 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes\r\n2022-08-25 19:51:12,455 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)\r\n2022-08-25 19:51:12,456 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)\r\n2022-08-25 19:51:12,456 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 8913 bytes\r\n2022-08-25 19:51:12,457 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/obj.pkl (recursive=False)\r\n2022-08-25 19:51:12,458 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/obj.pkl (recursive=False)\r\n2022-08"]
[19.137313, "o", "-25 19:51:12,458 - main.py[DEBUG]: [local] init will now be targeting instance id: ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a. new=True\r\n2022-08-25 19:51:12,458 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)\r\n2022-08-25 19:51:12,458 - util.py[DEBUG]: Read 1274 bytes from /etc/cloud/cloud.cfg\r\n2022-08-25 19:51:12,458 - util.py[DEBUG]: Attempting to load yaml from string of length 1274 with allowed root types (<class 'dict'>,)\r\n2022-08-25 19:51:12,463 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)\r\n2022-08-25 19:51:12,463 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg\r\n2022-08-25 19:51:12,463 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)\r\n2022-08-25 19:51:12,466 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)\r\n2022-08-25 19:51:12,466 - util.py[DEBUG]: Read 34 bytes from /run/cloud-init/cloud"]
[19.138169, "o", ".cfg\r\n2022-08-25 19:51:12,466 - util.py[DEBUG]: Attempting to load yaml from string of length 34 with allowed root types (<class 'dict'>,)\r\n2022-08-25 19:51:12,466 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)\r\n2022-08-25 19:51:12,466 - util.py[DEBUG]: loaded blob returned None, returning default.\r\n2022-08-25 19:51:12,467 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.rhel.Distro'>\r\n2022-08-25 19:51:12,468 - cc_set_hostname.py[DEBUG]: Setting the hostname to ampere-a1-almalinux-9-01 (ampere-a1-almalinux-9-01)\r\n2022-08-25 19:51:12,468 - subp.py[DEBUG]: Running command ['hostnamectl', 'set-hostname', 'ampere-a1-almalinux-9-01'] with allowed return codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:12,526 - __init__.py[DEBUG]: Non-persistently setting the system hostname to ampere-a1-almalinux-9-01\r\n2022-08-25 19:51:12,526 - subp.py[DEBUG]: Running command ['hostname', 'ampere-a1-almalinux-9-01'] with allowed return codes [0] (s"]
[19.139405, "o", "hell=False, capture=True)\r\n2022-08-25 19:51:12,532 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/set-hostname (via temporary file /var/lib/cloud/data/tmpipwwwgoe) - w: [644] 81 bytes/chars\r\n2022-08-25 19:51:12,533 - util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)\r\n2022-08-25 19:51:12,533 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address\r\n2022-08-25 19:51:12,533 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)\r\n2022-08-25 19:51:12,533 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address\r\n2022-08-25 19:51:12,533 - util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)\r\n2022-08-25 19:51:12,533 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address\r\n2022-08-25 19:51:12,533 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)\r\n2022-08-25 19:51:12,533 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address\r\n2022-08-25 19:51:12,533 - __init__.py[DEBUG]: Stable ifnames d"]
[19.140501, "o", "isabled by net.ifnames=0 in /proc/cmdline\r\n2022-08-25 19:51:12,533 - util.py[DEBUG]: Reading from /sys/class/net/eth0/carrier (quiet=False)\r\n2022-08-25 19:51:12,533 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/carrier\r\n2022-08-25 19:51:12,533 - util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)\r\n2022-08-25 19:51:12,533 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address\r\n2022-08-25 19:51:12,534 - util.py[DEBUG]: Reading from /sys/class/net/eth0/device/features (quiet=False)\r\n2022-08-25 19:51:12,534 - util.py[DEBUG]: Read 65 bytes from /sys/class/net/eth0/device/features\r\n2022-08-25 19:51:12,534 - util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)\r\n2022-08-25 19:51:12,534 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address\r\n2022-08-25 19:51:12,534 - util.py[DEBUG]: Reading from /sys/class/net/eth0/addr_assign_type (quiet=False)\r\n2022-08-25 19:51:12,534 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/addr_assign_type\r\n2022-08-2"]
[19.141234, "o", "5 19:51:12,534 - util.py[DEBUG]: Reading from /sys/class/net/eth0/uevent (quiet=False)\r\n2022-08-25 19:51:12,534 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/eth0/uevent\r\n2022-08-25 19:51:12,534 - util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)\r\n2022-08-25 19:51:12,534 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address\r\n2022-08-25 19:51:12,534 - util.py[DEBUG]: Reading from /sys/class/net/eth0/device/device (quiet=False)\r\n2022-08-25 19:51:12,534 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/eth0/device/device\r\n2022-08-25 19:51:12,534 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)\r\n2022-08-25 19:51:12,534 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type\r\n2022-08-25 19:51:12,534 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)\r\n2022-08-25 19:51:12,534 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent\r\n2022-08-25 19:51:12,534 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr"]
[19.142006, "o", "ess (quiet=False)\r\n2022-08-25 19:51:12,534 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address\r\n2022-08-25 19:51:12,534 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)\r\n2022-08-25 19:51:12,534 - util.py[DEBUG]: Reading from /sys/class/net/eth0/type (quiet=False)\r\n2022-08-25 19:51:12,534 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/type\r\n2022-08-25 19:51:12,534 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)\r\n2022-08-25 19:51:12,535 - util.py[DEBUG]: Read 4 bytes from /sys/class/net/lo/type\r\n2022-08-25 19:51:12,535 - util.py[DEBUG]: Reading from /sys/class/net/eth0/device/features (quiet=False)\r\n2022-08-25 19:51:12,535 - util.py[DEBUG]: Read 65 bytes from /sys/class/net/eth0/device/features\r\n2022-08-25 19:51:12,535 - util.py[DEBUG]: Reading from /sys/class/net/eth0/device/device (quiet=False)\r\n2022-08-25 19:51:12,535 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/eth0/device/device\r\n2022-08-25 19:51:12,535 - util.py[DEBUG]: Reading from"]
[19.142829, "o", " /sys/class/net/eth0/addr_assign_type (quiet=False)\r\n2022-08-25 19:51:12,535 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/addr_assign_type\r\n2022-08-25 19:51:12,535 - util.py[DEBUG]: Reading from /sys/class/net/eth0/uevent (quiet=False)\r\n2022-08-25 19:51:12,535 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/eth0/uevent\r\n2022-08-25 19:51:12,535 - util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)\r\n2022-08-25 19:51:12,535 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address\r\n2022-08-25 19:51:12,535 - util.py[DEBUG]: Reading from /sys/class/net/eth0/device/device (quiet=False)\r\n2022-08-25 19:51:12,535 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/eth0/device/device\r\n2022-08-25 19:51:12,535 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)\r\n2022-08-25 19:51:12,535 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type\r\n2022-08-25 19:51:12,535 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)\r\n2022"]
[19.143582, "o", "-08-25 19:51:12,535 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent\r\n2022-08-25 19:51:12,535 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)\r\n2022-08-25 19:51:12,535 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address\r\n2022-08-25 19:51:12,535 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)\r\n2022-08-25 19:51:12,535 - util.py[DEBUG]: Reading from /sys/class/net/eth0/type (quiet=False)\r\n2022-08-25 19:51:12,535 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/type\r\n2022-08-25 19:51:12,536 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)\r\n2022-08-25 19:51:12,536 - util.py[DEBUG]: Read 4 bytes from /sys/class/net/lo/type\r\n2022-08-25 19:51:12,536 - networking.py[DEBUG]: net: all expected physical devices present\r\n2022-08-25 19:51:12,536 - stages.py[DEBUG]: applying net config names for {'ethernets': {'eth0': {'dhcp4': True, 'set-name': 'eth0', 'match': {'macaddress': '02:00:17:00:b8:0c'}}}, 'version': 2}\r\n2022-08-2"]
[19.144297, "o", "5 19:51:12,536 - util.py[DEBUG]: Reading from /sys/class/net/eth0/device/device (quiet=False)\r\n2022-08-25 19:51:12,536 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/eth0/device/device\r\n2022-08-25 19:51:12,536 - util.py[DEBUG]: Reading from /sys/class/net/eth0/addr_assign_type (quiet=False)\r\n2022-08-25 19:51:12,536 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/addr_assign_type\r\n2022-08-25 19:51:12,536 - util.py[DEBUG]: Reading from /sys/class/net/eth0/uevent (quiet=False)\r\n2022-08-25 19:51:12,536 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/eth0/uevent\r\n2022-08-25 19:51:12,536 - util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)\r\n2022-08-25 19:51:12,536 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address\r\n2022-08-25 19:51:12,536 - util.py[DEBUG]: Reading from /sys/class/net/eth0/device/device (quiet=False)\r\n2022-08-25 19:51:12,536 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/eth0/device/device\r\n2022-08-25 19:51:12,536 - util.py[DEBUG]: Reading from /"]
[19.145074, "o", "sys/class/net/lo/addr_assign_type (quiet=False)\r\n2022-08-25 19:51:12,536 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type\r\n2022-08-25 19:51:12,536 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)\r\n2022-08-25 19:51:12,536 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent\r\n2022-08-25 19:51:12,536 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)\r\n2022-08-25 19:51:12,536 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address\r\n2022-08-25 19:51:12,536 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)\r\n2022-08-25 19:51:12,536 - util.py[DEBUG]: Reading from /sys/class/net/eth0/operstate (quiet=False)\r\n2022-08-25 19:51:12,536 - util.py[DEBUG]: Read 3 bytes from /sys/class/net/eth0/operstate\r\n2022-08-25 19:51:12,536 - util.py[DEBUG]: Reading from /sys/class/net/lo/operstate (quiet=False)\r\n2022-08-25 19:51:12,536 - util.py[DEBUG]: Read 8 bytes from /sys/class/net/lo/operstate\r\n2022-08-25 19:51:12,537 - subp.py"]
[19.145794, "o", "[DEBUG]: Running command ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] with allowed return codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:12,541 - subp.py[DEBUG]: Running command ['ip', '-4', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:12,545 - __init__.py[DEBUG]: no work necessary for renaming of [['02:00:17:00:b8:0c', 'eth0', 'virtio_net', '0x0001']]\r\n2022-08-25 19:51:12,546 - stages.py[INFO]: Applying network configuration from ds bringup=False: {'ethernets': {'eth0': {'dhcp4': True, 'set-name': 'eth0', 'match': {'macaddress': '02:00:17:00:b8:0c'}}}, 'version': 2}\r\n2022-08-25 19:51:12,546 - __init__.py[DEBUG]: Selected renderer 'sysconfig' from priority list: None\r\n2022-08-25 19:51:12,546 - network_state.py[DEBUG]: v2(ethernets) -> v1(physical):\r\n{'type': 'physical', 'name': 'eth0', 'mac_address': '02:00:17:00:b8:0c', 'match': {'macaddress': '02:00:17:00:b8:0c'}, 'subnets': [{'type': 'dhcp4'}]}\r\n2022-08-25 19:51:12,548 - network_state."]
[19.146642, "o", "py[DEBUG]: v2_common: handling config:\r\n{'eth0': {'dhcp4': True, 'set-name': 'eth0', 'match': {'macaddress': '02:00:17:00:b8:0c'}}}\r\n2022-08-25 19:51:12,549 - util.py[DEBUG]: Writing to /etc/sysconfig/network-scripts/ifcfg-eth0 - wb: [644] 184 bytes\r\n2022-08-25 19:51:12,551 - util.py[DEBUG]: Restoring selinux mode for /etc/sysconfig/network-scripts/ifcfg-eth0 (recursive=False)\r\n2022-08-25 19:51:12,552 - util.py[DEBUG]: Restoring selinux mode for /etc/sysconfig/network-scripts/ifcfg-eth0 (recursive=False)\r\n2022-08-25 19:51:12,552 - util.py[DEBUG]: Writing to /etc/udev/rules.d/70-persistent-net.rules - wb: [644] 96 bytes\r\n2022-08-25 19:51:12,553 - util.py[DEBUG]: Restoring selinux mode for /etc/udev/rules.d/70-persistent-net.rules (recursive=False)\r\n2022-08-25 19:51:12,553 - util.py[DEBUG]: Restoring selinux mode for /etc/udev/rules.d/70-persistent-net.rules (recursive=False)\r\n2022-08-25 19:51:12,555 - sysconfig.py[DEBUG]: Enabled ifcfg-rh NetworkManager plugins\r\n2022-08-25 19:51:12,555 - util.py[DEBUG]: Readin"]
[19.147808, "o", "g from /etc/sysconfig/network (quiet=True)\r\n2022-08-25 19:51:12,556 - util.py[DEBUG]: Read 52 bytes from /etc/sysconfig/network\r\n2022-08-25 19:51:12,556 - util.py[DEBUG]: Writing to /etc/sysconfig/network - wb: [644] 124 bytes\r\n2022-08-25 19:51:12,557 - util.py[DEBUG]: Restoring selinux mode for /etc/sysconfig/network (recursive=False)\r\n2022-08-25 19:51:12,558 - util.py[DEBUG]: Restoring selinux mode for /etc/sysconfig/network (recursive=False)\r\n2022-08-25 19:51:12,558 - main.py[DEBUG]: [local] Exiting. d"]
[19.149081, "o", "atasource DataSourceOracle not in local mode.\r\n2022-08-25 19:51:12,559 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpqbm100mw) - w: [644] 489 bytes/chars\r\n2022-08-25 19:51:12,559 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)\r\n2022-08-25 19:51:12,559 - util.py[DEBUG]: Read 12 bytes from /proc/uptime\r\n2022-08-25 19:51:12,559 - util.py[DEBUG]: cloud-init mode 'init' took 0.526 seconds (0.53)\r\n2022-08-25 19:51:12,559 - handlers.py[DEBUG]: finish: init-local: SUCCESS: searching for local datasources\r\n2022-08-25 19:51:13,518 - util.py[DEBUG]: Cloud-init v. 21.1-19.el9.alma running 'init' at Thu, 25 Aug 2022 19:51:13 +0000. Up 14.30 seconds.\r\n2022-08-25 19:51:13,518 - main.py[DEBUG]: No kernel command line url found.\r\n2022-08-25 19:51:13,518 - main.py[DEBUG]: Closing stdin.\r\n2022-08-25 19:51:13,519 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=False)\r\n2022-08-25 19:51:13,520 - util.py[DEBUG]: Resto"]
[19.149948, "o", "ring selinux mode for /var/lib/cloud/scripts (recursive=False)\r\n2022-08-25 19:51:13,520 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-instance (recursive=False)\r\n2022-08-25 19:51:13,521 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-once (recursive=False)\r\n2022-08-25 19:51:13,521 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-boot (recursive=False)\r\n2022-08-25 19:51:13,522 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/vendor (recursive=False)\r\n2022-08-25 19:51:13,522 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/seed (recursive=False)\r\n2022-08-25 19:51:13,523 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances (recursive=False)\r\n2022-08-25 19:51:13,523 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/handlers (recursive=False)\r\n2022-08-25 19:51:13,523 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/sem (recursive=False)\r\n2022-08-25 19:51:13,524 - util.py[DEBU"]
[19.150908, "o", "G]: Restoring selinux mode for /var/lib/cloud/data (recursive=False)\r\n2022-08-25 19:51:13,524 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes\r\n2022-08-25 19:51:13,526 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)\r\n2022-08-25 19:51:13,527 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)\r\n2022-08-25 19:51:13,527 - subp.py[DEBUG]: Running command ['ip', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:13,532 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:13,535 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)\r\n2022-08-25 19:51:13,539 - main.py[DEBUG]: Checking to see if files that we need already exist from a previous run that would allow us to stop early.\r\n2022-08-25 19:51"]
[19.151505, "o", ":13,539 - main.py[DEBUG]: Execution continuing, no previous run detected that would allow us to stop early.\r\n2022-08-25 19:51:13,539 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]\r\n2022-08-25 19:51:13,539 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)\r\n2022-08-25 19:51:13,539 - util.py[DEBUG]: Read 8913 bytes from /var/lib/cloud/instance/obj.pkl\r\n2022-08-25 19:51:13,542 - util.py[DEBUG]: Reading from /run/cloud-init/.instance-id (quiet=False)\r\n2022-08-25 19:51:13,542 - util.py[DEBUG]: Read 94 bytes from /run/cloud-init/.instance-id\r\n2022-08-25 19:51:13,542 - stages.py[DEBUG]: restored from cache with run check: DataSourceOracle\r\n2022-08-25 19:51:13,542 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: restored from cache with run check: DataSourceOracle\r\n2022-08-25 19:51:13,543 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)\r\n2022-08-25 19:51:13,543 - util.py[DEBUG]: Read 1274 bytes from /etc/cloud/clo"]
[19.151812, "o", "ud.cfg\r\n2022-08-25 19:51:13,543 - util.py[DEBUG]: Attempting to load yaml from string of length 1274 with allowed root types (<class 'dict'>,)\r\n2022-08-25 19:51:13,548 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)\r\n2022-08-25 19:51:13,548 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg\r\n2022-08-25 19:51:13,548 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)\r\n2022-08-25 19:51:13,551 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)\r\n2022-08-25 19:51:13,551 - util.py[DEBUG]: Read 34 bytes from /run/cloud-init/cloud.cfg\r\n2022-08-25 19:51:13,551 - util.py[DEBUG]: Attempting to load yaml from string of length 34 with allowed root types (<class 'dict'>,)\r\n2022-08-25 19:51:13,551 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)\r\n2022-08-25 19:51:13,551 - util.py[DEBUG]: loaded blob returned None, returning defa"]
[19.15277, "o", "ult.\r\n2022-08-25 19:51:13,552 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance\r\n2022-08-25 19:51:13,552 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a'\r\n2022-08-25 19:51:13,552 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/handlers (recursive=False)\r\n2022-08-25 19:51:13,553 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/scripts (recursive=False)\r\n2022-08-25 19:51:13,554 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem (recursive=False)\r\n2022-08-25 19:51:13,554 - util.py[DEBUG]: Reading from /var/lib/clo"]
[19.153331, "o", "ud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/datasource (quiet=False)\r\n2022-08-25 19:51:13,554 - util.py[DEBUG]: Read 35 bytes from /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/datasource\r\n2022-08-25 19:51:13,554 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/datasource - wb: [644] 35 bytes\r\n2022-08-25 19:51:13,555 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/datasource (recursive=False)\r\n2022-08-25 19:51:13,556 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/datasource (recursive=False)\r\n2022-08-25 19:51:13,557 - util.py[DEBUG]: Writing to /var/"]
[19.153553, "o", "lib/cloud/data/previous-datasource - wb: [644] 35 bytes\r\n2022-08-25 19:51:13,557 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)\r\n2022-08-25 19:51:13,558 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)\r\n2022-08-25 19:51:13,558 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)\r\n2022-08-25 19:51:13,558 - util.py[DEBUG]: Read 94 bytes from /var/lib/cloud/data/instance-id\r\n2022-08-25 19:51:13,558 - stages.py[DEBUG]: previous iid found to be ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a\r\n2022-08-25 19:51:13,558 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 94 bytes\r\n2022-08-25 19:51:13,559 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)\r\n2022-08-25 19:51:13,560 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)\r\n2022"]
[19.153685, "o", "-08-25 19:51:13,560 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 94 bytes\r\n2022-08-25 19:51:13,560 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)\r\n2022-08-25 19:51:13,561 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)\r\n2022-08-25 19:51:13,561 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 94 bytes\r\n2022-08-25 19:51:13,561 - util.py[DEBUG]: Restoring selinux mo"]
[19.169247, "o", "de for /var/lib/cloud/data/previous-instance-id (recursive=False)\r\n2022-08-25 19:51:13,562 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)\r\n2022-08-25 19:51:13,563 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 8919 bytes\r\n2022-08-25 19:51:13,563 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/obj.pkl (recursive=False)\r\n2022-08-25 19:51:13,564 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/obj.pkl (recursive=False)\r\n2022-08-25 19:51:13,565 - main.py[DEBUG]: [net] init will now be targeting instance id: ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a. new=False\r\n2022-08-25 19:51:13,565 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)\r\n2022"]
[19.169843, "o", "-08-25 19:51:13,565 - util.py[DEBUG]: Read 1274 bytes from /etc/cloud/cloud.cfg\r\n2022-08-25 19:51:13,565 - util.py[DEBUG]: Attempting to load yaml from string of length 1274 with allowed root types (<class 'dict'>,)\r\n2022-08-25 19:51:13,570 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)\r\n2022-08-25 19:51:13,570 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg\r\n2022-08-25 19:51:13,570 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)\r\n2022-08-25 19:51:13,572 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)\r\n2022-08-25 19:51:13,572 - util.py[DEBUG]: Read 34 bytes from /run/cloud-init/cloud.cfg\r\n2022-08-25 19:51:13,572 - util.py[DEBUG]: Attempting to load yaml from string of length 34 with allowed root types (<class 'dict'>,)\r\n2022-08-25 19:51:13,573 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)\r\n2022-08-25"]
[19.171385, "o", " 19:51:13,573 - util.py[DEBUG]: loaded blob returned None, returning default.\r\n2022-08-25 19:51:13,574 - util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)\r\n2022-08-25 19:51:13,574 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address\r\n2022-08-25 19:51:13,574 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)\r\n2022-08-25 19:51:13,574 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address\r\n2022-08-25 19:51:13,574 - util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)\r\n2022-08-25 19:51:13,574 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address\r\n2022-08-25 19:51:13,574 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)\r\n2022-08-25 19:51:13,574 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address\r\n2022-08-25 19:51:13,574 - __init__.py[DEBUG]: Stable ifnames disabled by net.ifnames=0 in /proc/cmdline\r\n2022-08-25 19:51:13,575 - util.py[DEBUG]: Reading from /sys/class/net/eth0/carrier (quiet=False)"]
[19.172132, "o", "\r\n2022-08-25 19:51:13,575 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/carrier\r\n2022-08-25 19:51:13,575 - util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)\r\n2022-08-25 19:51:13,575 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address\r\n2022-08-25 19:51:13,575 - util.py[DEBUG]: Reading from /sys/class/net/eth0/device/features (quiet=False)\r\n2022-08-25 19:51:13,575 - util.py[DEBUG]: Read 65 bytes from /sys/class/net/eth0/device/features\r\n2022-08-25 19:51:13,575 - util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)\r\n2022-08-25 19:51:13,575 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address\r\n2022-08-25 19:51:13,575 - util.py[DEBUG]: Reading from /sys/class/net/eth0/addr_assign_type (quiet=False)\r\n2022-08-25 19:51:13,575 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/addr_assign_type\r\n2022-08-25 19:51:13,575 - util.py[DEBUG]: Reading from /sys/class/net/eth0/uevent (quiet=False)\r\n2022-08-25 19:51:13,575 - util.py[DEBUG]: Read 25 b"]
[19.17294, "o", "ytes from /sys/class/net/eth0/uevent\r\n2022-08-25 19:51:13,575 - util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)\r\n2022-08-25 19:51:13,575 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address\r\n2022-08-25 19:51:13,575 - util.py[DEBUG]: Reading from /sys/class/net/eth0/device/device (quiet=False)\r\n2022-08-25 19:51:13,575 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/eth0/device/device\r\n2022-08-25 19:51:13,575 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)\r\n2022-08-25 19:51:13,575 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type\r\n2022-08-25 19:51:13,575 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)\r\n2022-08-25 19:51:13,575 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent\r\n2022-08-25 19:51:13,575 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)\r\n2022-08-25 19:51:13,576 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address\r\n2022-08-25 19:51:13,576 - util.p"]
[19.173653, "o", "y[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)\r\n2022-08-25 19:51:13,576 - util.py[DEBUG]: Reading from /sys/class/net/eth0/type (quiet=False)\r\n2022-08-25 19:51:13,576 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/type\r\n2022-08-25 19:51:13,576 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)\r\n2022-08-25 19:51:13,576 - util.py[DEBUG]: Read 4 bytes from /sys/class/net/lo/type\r\n2022-08-25 19:51:13,576 - util.py[DEBUG]: Reading from /sys/class/net/eth0/device/features (quiet=False)\r\n2022-08-25 19:51:13,576 - util.py[DEBUG]: Read 65 bytes from /sys/class/net/eth0/device/features\r\n2022-08-25 19:51:13,576 - __init__.py[DEBUG]: Datasource DataSourceOracle not updated for events: System boot\r\n2022-08-25 19:51:13,576 - stages.py[DEBUG]: No network config applied. Neither a new instance nor datasource network update on 'System boot' event\r\n2022-08-25 19:51:13,576 - stages.py[DEBUG]: applying net config names for {'ethernets': {'eth0': {'dhcp4': True, 'set-name': 'eth0', "]
[19.174403, "o", "'match': {'macaddress': '02:00:17:00:b8:0c'}}}, 'version': 2}\r\n2022-08-25 19:51:13,576 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.rhel.Distro'>\r\n2022-08-25 19:51:13,577 - util.py[DEBUG]: Reading from /sys/class/net/eth0/device/device (quiet=False)\r\n2022-08-25 19:51:13,577 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/eth0/device/device\r\n2022-08-25 19:51:13,577 - util.py[DEBUG]: Reading from /sys/class/net/eth0/addr_assign_type (quiet=False)\r\n2022-08-25 19:51:13,577 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/addr_assign_type\r\n2022-08-25 19:51:13,577 - util.py[DEBUG]: Reading from /sys/class/net/eth0/uevent (quiet=False)\r\n2022-08-25 19:51:13,577 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/eth0/uevent\r\n2022-08-25 19:51:13,577 - util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)\r\n2022-08-25 19:51:13,577 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address\r\n2022-08-25 19:51:13,577 - util.py[DEBUG]: Reading from /sys/class/net/eth0/devi"]
[19.175086, "o", "ce/device (quiet=False)\r\n2022-08-25 19:51:13,577 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/eth0/device/device\r\n2022-08-25 19:51:13,577 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)\r\n2022-08-25 19:51:13,577 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type\r\n2022-08-25 19:51:13,577 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)\r\n2022-08-25 19:51:13,577 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent\r\n2022-08-25 19:51:13,577 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)\r\n2022-08-25 19:51:13,577 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address\r\n2022-08-25 19:51:13,577 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)\r\n2022-08-25 19:51:13,577 - util.py[DEBUG]: Reading from /sys/class/net/eth0/operstate (quiet=False)\r\n2022-08-25 19:51:13,577 - util.py[DEBUG]: Read 3 bytes from /sys/class/net/eth0/operstate\r\n2022-08-25 19:51:13,577 - util.py[DEBUG]: Re"]
[19.17577, "o", "ading from /sys/class/net/lo/operstate (quiet=False)\r\n2022-08-25 19:51:13,577 - util.py[DEBUG]: Read 8 bytes from /sys/class/net/lo/operstate\r\n2022-08-25 19:51:13,578 - subp.py[DEBUG]: Running command ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] with allowed return codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:13,580 - subp.py[DEBUG]: Running command ['ip', '-4', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:13,583 - __init__.py[DEBUG]: no work necessary for renaming of [['02:00:17:00:b8:0c', 'eth0', 'virtio_net', '0x0001']]\r\n2022-08-25 19:51:13,584 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource\r\n2022-08-25 19:51:13,584 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource\r\n2022-08-25 19:51:13,584 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/user-data.txt - wb: [600"]
[19.176363, "o", "] 1288 bytes\r\n2022-08-25 19:51:13,585 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/user-data.txt (recursive=False)\r\n2022-08-25 19:51:13,586 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/user-data.txt (recursive=False)\r\n2022-08-25 19:51:13,588 - util.py[DEBUG]: Attempting to "]
[19.177005, "o", "load yaml from string of length 1288 with allowed root types (<class 'dict'>,)\r\n2022-08-25 19:51:13,594 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/user-data.txt.i - wb: [600] 1593 bytes\r\n2022-08-25 19:51:13,594 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/user-data.txt.i (recursive=False)\r\n2022-08-25 19:51:13,595 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/user-data.txt.i (recursive=False)\r\n2022-08-25 19:51:13,596 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/vendor-data.txt - wb: [600] 0 bytes\r\n2022-08-25 19:51:13,596 - util.py[DEBUG]: Restoring selinux mode for /var/lib"]
[19.17786, "o", "/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/vendor-data.txt (recursive=False)\r\n2022-08-25 19:51:13,597 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/vendor-data.txt (recursive=False)\r\n2022-08-25 19:51:13,598 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/vendor-data.txt.i - wb: [600] 308 bytes\r\n2022-08-25 19:51:13,598 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/vendor-data.txt.i (recursive=False)\r\n2022-08-25 19:51:13,599 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/vendor-data.txt.i (recursive="]
[19.17871, "o", "False)\r\n2022-08-25 19:51:13,600 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/vendor-data2.txt - wb: [600] 0 bytes\r\n2022-08-25 19:51:13,600 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/vendor-data2.txt (recursive=False)\r\n2022-08-25 19:51:13,601 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/vendor-data2.txt (recursive=False)\r\n2022-08-25 19:51:13,602 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/vendor-data2.txt.i - wb: [600] 308 bytes\r\n2022-08-25 19:51:13,603 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxich"]
[19.179391, "o", "rcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/vendor-data2.txt.i (recursive=False)\r\n2022-08-25 19:51:13,603 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/vendor-data2.txt.i (recursive=False)\r\n2022-08-25 19:51:13,604 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)\r\n2022-08-25 19:51:13,604 - util.py[DEBUG]: Read 81 bytes from /var/lib/cloud/data/set-hostname\r\n2022-08-25 19:51:13,604 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname\r\n2022-08-25 19:51:13,605 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/consume_data - wb: [644] 25 bytes\r\n2022-08-25 19:51:13,605 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/consume_data (recu"]
[19.180088, "o", "rsive=False)\r\n2022-08-25 19:51:13,606 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/consume_data (recursive=False)\r\n2022-08-25 19:51:13,606 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/consume_data'>)\r\n2022-08-25 19:51:13,607 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data\r\n2022-08-25 19:51:13,607 - launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0\r\n2022-08-25 19:51:13,607 - stages.py[DEBUG]: Added default handler for {'text/cloud-config', 'text/cloud-config-jsonp'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]\r\n2022-08-25 19:51:13,607 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPar"]
[19.180759, "o", "tHandler: [['text/x-shellscript']]\r\n2022-08-25 19:51:13,607 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]\r\n2022-08-25 19:51:13,607 - stages.py[DEBUG]: Added default handler for {'text/upstart-job'} from UpstartJobPartHandler: [['text/upstart-job']]\r\n2022-08-25 19:51:13,607 - stages.py[DEBUG]: Added default handler for {'text/jinja2'} from JinjaTemplatePartHandler: [['text/jinja2']]\r\n2022-08-25 19:51:13,607 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance\r\n2022-08-25 19:51:13,607 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance\r\n2022-08-25 19:51:13,608 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance\r\n2022-08-25 19:51:13,608 - __init__.py[DE"]
[19.181805, "o", "BUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__begin__, None, 2) with frequency once-per-instance\r\n2022-08-25 19:51:13,608 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance\r\n2022-08-25 19:51:13,608 - __init__.py[DEBUG]: {'MIME-Version': '1.0', 'Content-Type': 'text/cloud-config', 'Content-Disposition': 'attachment; filename=\"part-001\"'}\r\n2022-08-25 19:51:13,608 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (text/cloud-config, part-001, 3) with frequency once-per-instance\r\n2022-08-25 19:51:13,608 - util.py[DEBUG]: Attempting to load yaml from string of length 1288 with allowed root types (<class 'dict'>,)\r\n2022-08-25 19:51:13,611 - cloud_config.py[DEBUG]: Merging by applying [('dict', ['replace']), ('list', []), ('str', [])]\r\n2022-08-25 19:51:13,611 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'te"]
[19.18277, "o", "xt/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance\r\n2022-08-25 19:51:13,614 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/cloud-config.txt - wb: [600] 1268 bytes\r\n2022-08-25 19:51:13,614 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/cloud-config.txt (recursive=False)\r\n2022-08-25 19:51:13,615 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/cloud-config.txt (recursive=False)\r\n2022-08-25 19:51:13,615 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance\r\n2022-08-25 19:51:13,615 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, No"]
[19.183691, "o", "ne, 2) with frequency once-per-instance\r\n2022-08-25 19:51:13,615 - __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__end__, None, 2) with frequency once-per-instance\r\n2022-08-25 19:51:13,616 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance\r\n2022-08-25 19:51:13,616 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data\r\n2022-08-25 19:51:13,616 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data\r\n2022-08-25 19:51:13,616 - stages.py[DEBUG]: no vendordata from datasource\r\n2022-08-25 19:51:13,616 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data\r\n2022-08-25 19:51:13,616 - handlers.py[DEBUG]: start: init-network/consume-vendor-data2: reading and applying vendor-data2\r\n2022-08-25 19:51:13,616 - stages.py[DEBUG]: no vendordata2 from datasource\r\n2022-08-25"]
[19.184432, "o", " 19:51:13,616 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data2: SUCCESS: reading and applying vendor-data2\r\n2022-08-25 19:51:13,616 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)\r\n2022-08-25 19:51:13,616 - util.py[DEBUG]: Read 1274 bytes from /etc/cloud/cloud.cfg\r\n2022-08-25 19:51:13,616 - util.py[DEBUG]: Attempting to load yaml from string of length 1274 with allowed root types (<class 'dict'>,)\r\n2022-08-25 19:51:13,621 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)\r\n2022-08-25 19:51:13,621 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg\r\n2022-08-25 19:51:13,621 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)\r\n2022-08-25 19:51:13,624 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)\r\n2022-08-25 19:51:13,624 - util.py[DEBUG]: Read 34 bytes from /run/cloud-init/cloud.cfg\r\n2022-08-25 19:51:13,624 - util.py[DEBUG]: Attempting to loa"]
[19.185404, "o", "d yaml from string of length 34 with allowed root types (<class 'dict'>,)\r\n2022-08-25 19:51:13,624 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)\r\n2022-08-25 19:51:13,624 - util.py[DEBUG]: loaded blob returned None, returning default.\r\n2022-08-25 19:51:13,624 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)\r\n2022-08-25 19:51:13,624 - util.py[DEBUG]: Read 1268 bytes from /var/lib/cloud/instance/cloud-config.txt\r\n2022-08-25 19:51:13,624 - util.py[DEBUG]: Attempting to load yaml from string of length 1268 with allowed root types (<class 'dict'>,)\r\n2022-08-25 19:51:13,628 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)\r\n2022-08-25 19:51:13,628 - util.py[DEBUG]: Read 1268 bytes from /var/lib/cloud/instance/cloud-config.txt\r\n2022-08-25 19:51:13,628 - util.py[DEBUG]: Attempting to load yaml from string of length 1268 with allowed root types (<class 'dict'>,)\r\n2022-08-25 19:51:13,634"]
[19.187547, "o", " - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource\r\n2022-08-25 19:51:13,634 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 12381 bytes\r\n2022-08-25 19:51:13,635 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/obj.pkl (recursive=False)\r\n2022-08-25 19:51:13,636 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/obj.pkl (recursive=False)\r\n2022-08-25 19:51:13,636 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource\r\n2022-08-25 19:51:13,636 - main.py[DEBUG]: no di_report found in config.\r\n2022-08-25 19:51:13,655 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.rhel.Distro'>\r\n2022-08-25 19:51:13,655 - stages.py[DEBUG]: Running module disk_setup (<module 'cloudinit.config.cc_"]
[19.188667, "o", "disk_setup' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disk_setup.py'>) with frequency once-per-instance\r\n2022-08-25 19:51:13,656 - handlers.py[DEBUG]: start: init-network/config-disk_setup: running config-disk_setup with frequency once-per-instance\r\n2022-08-25 19:51:13,656 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_disk_setup - wb: [644] 25 bytes\r\n2022-08-25 19:51:13,656 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_disk_setup (recursive=False)\r\n2022-08-25 19:51:13,657 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_disk_setup (recursive=False)\r\n2022-08-25 19:51:13,657 - helpers.py[DEBUG]: Running config-disk_setup using lock ("]
[19.189582, "o", "<FileLock using file '/var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_disk_setup'>)\r\n2022-08-25 19:51:13,658 - handlers.py[DEBUG]: finish: init-network/config-disk_setup: SUCCESS: config-disk_setup ran successfully\r\n2022-08-25 19:51:13,658 - stages.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_migrator.py'>) with frequency always\r\n2022-08-25 19:51:13,658 - handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always\r\n2022-08-25 19:51:13,658 - helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0xffff9d25d250>)\r\n2022-08-25 19:51:13,658 - cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names\r\n2022-08-25 19:51:13,658 - handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully\r\n2022-08-25 19:51:13,"]
[19.190861, "o", "658 - stages.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_bootcmd.py'>) with frequency always\r\n2022-08-25 19:51:13,658 - handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always\r\n2022-08-25 19:51:13,658 - helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0xffff9d25d670>)\r\n2022-08-25 19:51:13,658 - cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration\r\n2022-08-25 19:51:13,658 - handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully\r\n2022-08-25 19:51:13,658 - stages.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_files.py'>) with frequency once-per-instance\r\n2022-08-25 19:51:13,658 - handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files "]
[19.191798, "o", "with frequency once-per-instance\r\n2022-08-25 19:51:13,659 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_write_files - wb: [644] 25 bytes\r\n2022-08-25 19:51:13,659 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_write_files (recursive=False)\r\n2022-08-25 19:51:13,660 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_write_files (recursive=False)\r\n2022-08-25 19:51:13,660 - helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_write_files'>)\r\n2022-08-25 19:51:13,660 - cc_write_files.py[DEBUG]: Skipping "]
[19.192515, "o", "module named write-files, no/empty 'write_files' key in configuration\r\n2022-08-25 19:51:13,660 - handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files ran successfully\r\n2022-08-25 19:51:13,661 - stages.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_growpart.py'>) with frequency always\r\n2022-08-25 19:51:13,661 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always\r\n2022-08-25 19:51:13,661 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0xffff9d25da90>)\r\n2022-08-25 19:51:13,661 - cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'mode': 'auto', 'devices': ['/'], 'ignore_growroot_disabled': False}\r\n2022-08-25 19:51:13,661 - subp.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:13,668 - util.py[DEBUG]: R"]
[19.193302, "o", "eading from /proc/1035/mountinfo (quiet=False)\r\n2022-08-25 19:51:13,668 - util.py[DEBUG]: Read 2411 bytes from /proc/1035/mountinfo\r\n2022-08-25 19:51:13,668 - util.py[DEBUG]: Reading from /sys/class/block/sda3/partition (quiet=False)\r\n2022-08-25 19:51:13,668 - util.py[DEBUG]: Read 2 bytes from /sys/class/block/sda3/partition\r\n2022-08-25 19:51:13,668 - util.py[DEBUG]: Reading from /sys/devices/pci0000:00/0000:00:12.7/0000:18:00.0/virtio2/host0/target0:0:0/0:0:0:1/block/sda/dev (quiet=False)\r\n2022-08-25 19:51:13,668 - util.py[DEBUG]: Read 4 bytes from /sys/devices/pci0000:00/0000:00:12.7/0000:18:00.0/virtio2/host0/target0:0:0/0:0:0:1/block/sda/dev\r\n2022-08-25 19:51:13,669 - subp.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/sda', '3'] with allowed return codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:13,726 - subp.py[DEBUG]: Running command ['growpart', '/dev/sda', '3'] with allowed return codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:14,058 - util.py[DEBUG]: resize_devices took "]
[19.194016, "o", "0.388 seconds\r\n2022-08-25 19:51:14,059 - cc_growpart.py[INFO]: '/' resized: changed (/dev/sda, 3) from 8388608000 to 49275715072\r\n2022-08-25 19:51:14,059 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully\r\n2022-08-25 19:51:14,059 - stages.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_resizefs.py'>) with frequency always\r\n2022-08-25 19:51:14,060 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always\r\n2022-08-25 19:51:14,060 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0xffff9d25dac0>)\r\n2022-08-25 19:51:14,060 - schema.py[DEBUG]: Ignoring schema validation. python-jsonschema is not present\r\n2022-08-25 19:51:14,060 - util.py[DEBUG]: Reading from /proc/1035/mountinfo (quiet=False)\r\n2022-08-25 19:51:14,060 - util.py[DEBUG]: Read 2411 bytes from /proc/1035/mountinfo\r\n2022-08-25 1"]
[19.194996, "o", "9:51:14,060 - cc_resizefs.py[DEBUG]: resize_info: dev=/dev/sda3 mnt_point=/ path=/\r\n2022-08-25 19:51:14,060 - cc_resizefs.py[DEBUG]: Resizing / (xfs) using xfs_growfs /\r\n2022-08-25 19:51:14,060 - subp.py[DEBUG]: Running command ('xfs_growfs', '/') with allowed return codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:14,093 - util.py[DEBUG]: Resizing took 0.032 seconds\r\n2022-08-25 19:51:14,093 - cc_resizefs.py[DEBUG]: Resized root filesystem (type=xfs, val=True)\r\n2022-08-25 19:51:14,093 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully\r\n2022-08-25 19:51:14,093 - stages.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_hostname.py'>) with frequency once-per-instance\r\n2022-08-25 19:51:14,094 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency once-per-instance\r\n2022-08-25 19:51:14,094 - util.py[DEBUG]: Writi"]
[19.195742, "o", "ng to /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_set_hostname - wb: [644] 25 bytes\r\n2022-08-25 19:51:14,095 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_set_hostname (recursive=False)\r\n2022-08-25 19:51:14,097 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_set_hostname (recursive=False)\r\n2022-08-25 19:51:14,097 - helpers.py[DEBUG]: Running config-set_hostname using lock (<FileLock using file '/var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_set_hostname'>)\r\n2022-08-25 19:51:14,097 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)\r\n2022-08-25 19:51:14,097 - util.py["]
[19.196424, "o", "DEBUG]: Read 81 bytes from /var/lib/cloud/data/set-hostname\r\n2022-08-25 19:51:14,097 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname\r\n2022-08-25 19:51:14,097 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully\r\n2022-08-25 19:51:14,097 - stages.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always\r\n2022-08-25 19:51:14,098 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always\r\n2022-08-25 19:51:14,098 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0xffff9d25d130>)\r\n2022-08-25 19:51:14,098 - cc_update_hostname.py[DEBUG]: Updating hostname to ampere-a1-almalinux-9-01 (ampere-a1-almalinux-9-01)\r\n2022-08-25 19:51:14,098 - subp.py[DEBUG]: Running command ['hostname'] with allowed re"]
[19.197129, "o", "turn codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:14,104 - __init__.py[DEBUG]: Attempting to update hostname to ampere-a1-almalinux-9-01 in 1 files\r\n2022-08-25 19:51:14,104 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 24 bytes\r\n2022-08-25 19:51:14,105 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)\r\n2022-08-25 19:51:14,106 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)\r\n2022-08-25 19:51:14,107 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully\r\n2022-08-25 19:51:14,107 - stages.py[DEBUG]: Running module update_etc_hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_etc_hosts.py'>) with frequency always\r\n2022-08-25 19:51:14,107 - handlers.py[DEBUG]: start: init-network/config-update_etc_hosts: running config-update_etc_hosts with f"]
[19.19782, "o", "requency always\r\n2022-08-25 19:51:14,107 - helpers.py[DEBUG]: Running config-update_etc_hosts using lock (<cloudinit.helpers.DummyLock object at 0xffff9d25d670>)\r\n2022-08-25 19:51:14,107 - cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update_etc_hosts\r\n2022-08-25 19:51:14,107 - handlers.py[DEBUG]: finish: init-network/config-update_etc_hosts: SUCCESS: config-update_etc_hosts ran successfully\r\n2022-08-25 19:51:14,107 - stages.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_rsyslog.py'>) with frequency once-per-instance\r\n2022-08-25 19:51:14,108 - handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance\r\n2022-08-25 19:51:14,108 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_rsyslog - wb: [644] 25"]
[19.199025, "o", " bytes\r\n2022-08-25 19:51:14,108 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_rsyslog (recursive=False)\r\n2022-08-25 19:51:14,109 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_rsyslog (recursive=False)\r\n2022-08-25 19:51:14,109 - helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_rsyslog'>)\r\n2022-08-25 19:51:14,110 - cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration\r\n2022-08-25 19:51:14,110 - handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog ran successfully\r\n2022-08-25 19:51:14,110 - stages.py[DEBUG]: Running module users-groups (<module "]
[19.199871, "o", "'cloudinit.config.cc_users_groups' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance\r\n2022-08-25 19:51:14,110 - handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance\r\n2022-08-25 19:51:14,110 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_users_groups - wb: [644] 24 bytes\r\n2022-08-25 19:51:14,110 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_users_groups (recursive=False)\r\n2022-08-25 19:51:14,111 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_users_groups (recursive=False)\r\n2022-08-25 19:51:14,112 - helpers.py[DEBUG]: Run"]
[19.200935, "o", "ning config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_users_groups'>)\r\n2022-08-25 19:51:14,112 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)\r\n2022-08-25 19:51:14,112 - util.py[DEBUG]: Read 549 bytes from /etc/os-release\r\n2022-08-25 19:51:14,113 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)\r\n2022-08-25 19:51:14,113 - util.py[DEBUG]: Read 0 bytes from /etc/system-image/channel.ini\r\n2022-08-25 19:51:14,115 - subp.py[DEBUG]: Running command ['groupadd', 'docker'] with allowed return codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:14,206 - __init__.py[INFO]: Created new group docker\r\n2022-08-25 19:51:14,207 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)\r\n2022-08-25 19:51:14,207 - util.py[DEBUG]: Read 549 bytes from /etc/os-release\r\n2022-08-25 19:51:14,208 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (qui"]
[19.201691, "o", "et=True)\r\n2022-08-25 19:51:14,208 - util.py[DEBUG]: Read 0 bytes from /etc/system-image/channel.ini\r\n2022-08-25 19:51:14,208 - __init__.py[DEBUG]: Adding user opc\r\n2022-08-25 19:51:14,208 - subp.py[DEBUG]: Running hidden command to protect sensitive input/output logstring: ['useradd', 'opc', '--comment', 'Cloud User', '--groups', 'docker', '--shell', '/bin/bash', '-m']\r\n2022-08-25 19:51:14,287 - subp.py[DEBUG]: Running command ['passwd', '-l', 'opc'] with allowed return codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:14,316 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)\r\n2022-08-25 19:51:14,317 - util.py[DEBUG]: Read 4328 bytes from /etc/sudoers\r\n2022-08-25 19:51:14,319 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d (recursive=False)\r\n2022-08-25 19:51:14,320 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - wb: [440] 128 bytes\r\n2022-08-25 19:51:14,321 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d/90-cloud-init-users (recursive=False)\r\n2022-08-25 19"]
[19.201948, "o", ":51:14,323 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d/90-cloud-init-users (recursive=False)\r\n2022-08-25 19:51:14,323 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully\r\n2022-08-25 19:51:14,323 - stages.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance\r\n2022-08-25 19:51:14,324 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance\r\n2022-08-25 19:51:14,324 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_ssh - wb: [644] 24 bytes\r\n2022-08-25 19:51:14,325 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_ssh (recursive=False)\r\n2022-08-25 19:51"]
[19.203348, "o", ":14,326 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_ssh (recursive=False)\r\n2022-08-25 19:51:14,326 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_ssh'>)\r\n2022-08-25 19:51:14,327 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'rsa', '-N', '', '-f', '/etc/ssh/ssh_host_rsa_key'] with allowed return codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:15,247 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)\r\n2022-08-25 19:51:15,260 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:15,268 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)\r\n2022-0"]
[19.204085, "o", "8-25 19:51:15,273 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:15,281 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)\r\n2022-08-25 19:51:15,287 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_rsa_key.pub (quiet=False)\r\n2022-08-25 19:51:15,287 - util.py[DEBUG]: Read 583 bytes from /etc/ssh/ssh_host_rsa_key.pub\r\n2022-08-25 19:51:15,287 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ecdsa_key.pub (quiet=False)\r\n2022-08-25 19:51:15,287 - util.py[DEBUG]: Read 191 bytes from /etc/ssh/ssh_host_ecdsa_key.pub\r\n2022-08-25 19:51:15,287 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ed25519_key.pub (quiet=False)\r\n2022-08-25 19:51:15,287 - util.py[DEBUG]: Read 111 bytes from /etc/ssh/ssh_host_ed25519_key.pub\r\n2022-08-25 19:51:15,288 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)\r\n2022-08-25 19:51:15,289 - util.py[DEBUG]: Read 3669 by"]
[19.205245, "o", "tes from /etc/ssh/sshd_config\r\n2022-08-25 19:51:15,289 - util.py[DEBUG]: Changing the ownership of /home/opc/.ssh to 1000:1001\r\n2022-08-25 19:51:15,290 - util.py[DEBUG]: Restoring selinux mode for /home/opc/.ssh (recursive=False)\r\n2022-08-25 19:51:15,290 - util.py[DEBUG]: Writing to /home/opc/.ssh/authorized_keys - wb: [600] 0 bytes\r\n2022-08-25 19:51:15,290 - util.py[DEBUG]: Restoring selinux mode for /home/opc/.ssh/authorized_keys (recursive=False)\r\n2022-08-25 19:51:15,291 - util.py[DEBUG]: Restoring selinux mode for /home/opc/.ssh/authorized_keys (recursive=False)\r\n2022-08-25 19:51:15,291 - util.py[DEBUG]: Changing the ownership of /home/opc/.ssh/authorized_keys to 1000:1001\r\n2022-08-25 19:51:15,291 - util.py[DEBUG]: Reading from /home/opc/.ssh/authorized_keys (quiet=False)\r\n2022-08-25 19:51:15,291 - util.py[DEBUG]: Read 0 bytes from /home/opc/.ssh/authorized_keys\r\n2022-08-25 19:51:15,291 - util.py[DEBUG]: Writing to /home/opc/.ssh/authorized_keys - wb: [600] 725 bytes\r\n2022-08-25 19:51:15,291 - util.py[DEB"]
[19.205936, "o", "UG]: Restoring selinux mode for /home/opc/.ssh/authorized_keys (recursive=False)\r\n2022-08-25 19:51:15,291 - util.py[DEBUG]: Restoring selinux mode for /home/opc/.ssh/authorized_keys (recursive=False)\r\n2022-08-25 19:51:15,292 - util.py[DEBUG]: Restoring selinux mode for /home/opc/.ssh (recursive=True)\r\n2022-08-25 19:51:15,293 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)\r\n2022-08-25 19:51:15,293 - util.py[DEBUG]: Read 3669 bytes from /etc/ssh/sshd_config\r\n2022-08-25 19:51:15,293 - util.py[DEBUG]: Changing the ownership of /root/.ssh to 0:0\r\n2022-08-25 19:51:15,293 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=False)\r\n2022-08-25 19:51:15,293 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes\r\n2022-08-25 19:51:15,294 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)\r\n2022-08-25 19:51:15,294 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)\r\n2022-08-25 19:51:15,294 - ut"]
[19.206288, "o", "il.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0\r\n2022-08-25 19:51:15,294 - util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)\r\n2022-08-25 19:51:15,294 - util.py[DEBUG]: Read 0 bytes from /root/.ssh/authorized_keys\r\n2022-08-25 19:51:15,294 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 886 bytes\r\n2022-08-25 19:51:15,294 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)\r\n2022-08-25 19:51:15,294 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)\r\n2022-08-25 19:51:15,295 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)\r\n2022-08-25 19:51:15,296 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully\r\n2022-08-25 19:51:15,296 - main.py[DEBUG]: Ran 12 modules with 0 failures\r\n2022-08-25 19:51:15,296 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/clo"]
[19.206484, "o", "ud/data/tmpbh86h_67) - w: [644] 517 bytes/chars\r\n2022-08-25 19:51:15,297 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)\r\n2022-08-25 19:51:15,297 - util.py[DEBUG]: Read 12 bytes from /proc/uptime\r\n2022-08-25 19:51:15,297 - util.py[DEBUG]: cloud-init mode 'init' took 1.820 seconds (1.82)\r\n2022-08-25 19:51:15,297 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources\r\n2022-08-25 19:51:15,631 - util.py[DEBUG]: Cloud-init v. 21.1-19.el9.alma running 'modules:config' at Thu, 25 Aug 2022 19:51:15 +0000. Up 16.38 seconds.\r\n2022-08-25 19:51:15,646 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.rhel.Distro'>\r\n2022-08-25 19:51:15,647 - stages.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance\r\n2022-08-25 19:51:15,647 - handlers.py[DEBUG]: start: modules-config/config-mounts: running config-mounts with frequency once-per-instance\r\n2022-08"]
[19.206707, "o", "-25 19:51:15,647 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_mounts - wb: [644] 25 bytes\r\n2022-08-25 19:51:15,649 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_mounts (recursive=False)\r\n2022-08-25 19:51:15,651 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_mounts (recursive=False)\r\n2022-08-25 19:51:15,651 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_mounts'>)\r\n2022-08-25 19:51:15,651 - cc_mounts.py[DEBUG]: mounts configuration is []\r\n2022-08-25 19:51:15,651 - util.py[DEBUG]: Reading fr"]
[19.207806, "o", "om /etc/fstab (quiet=False)\r\n2022-08-25 19:51:15,652 - util.py[DEBUG]: Read 628 bytes from /etc/fstab\r\n2022-08-25 19:51:15,652 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0\r\n2022-08-25 19:51:15,652 - cc_mounts.py[DEBUG]: changed default device ephemeral0 => None\r\n2022-08-25 19:51:15,652 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0\r\n2022-08-25 19:51:15,652 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap\r\n2022-08-25 19:51:15,652 - cc_mounts.py[DEBUG]: changed default device swap => None\r\n2022-08-25 19:51:15,652 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap\r\n2022-08-25 19:51:15,652 - cc_mounts.py[DEBUG]: no need to setup swap\r\n2022-08-25 19:51:15,652 - cc_mounts.py[DEBUG]: No modifications to fstab needed\r\n2022-08-25 19:51:15,652 - handlers.py[DEBUG]: finish: modules-config/config-mounts: SUCCESS: config-mounts ran successfully\r\n2022-08-25 19:51:15,652 - stages.py[DEBUG]: Running module locale (<module 'cloudin"]
[19.208504, "o", "it.config.cc_locale' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance\r\n2022-08-25 19:51:15,652 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance\r\n2022-08-25 19:51:15,652 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_locale - wb: [644] 25 bytes\r\n2022-08-25 19:51:15,653 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_locale (recursive=False)\r\n2022-08-25 19:51:15,653 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_locale (recursive=False)\r\n2022-08-25 19:51:15,654 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using f"]
[19.209102, "o", "ile '/var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_locale'>)\r\n2022-08-25 19:51:15,654 - schema.py[DEBUG]: Ignoring schema validation. python-jsonschema is not present\r\n2022-08-25 19:51:15,654 - cc_locale.py[DEBUG]: Setting locale to C.UTF-8\r\n2022-08-25 19:51:15,654 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)\r\n2022-08-25 19:51:15,654 - util.py[DEBUG]: Read 15 bytes from /etc/locale.conf\r\n2022-08-25 19:51:15,654 - util.py[DEBUG]: Writing to /etc/locale.conf - wb: [644] 13 bytes\r\n2022-08-25 19:51:15,656 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)\r\n2022-08-25 19:51:15,657 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)\r\n2022-08-25 19:51:15,658 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully\r\n2022-08-25 19:51:15,658 - stages.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_se"]
[19.209393, "o", "t_passwords' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance\r\n2022-08-25 19:51:15,658 - handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance\r\n2022-08-25 19:51:15,658 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_set_passwords - wb: [644] 25 bytes\r\n2022-08-25 19:51:15,658 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_set_passwords (recursive=False)\r\n2022-08-25 19:51:15,659 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_set_passwords (recursive=False)\r\n2022-08-25 19:51:15,660 - helpers.py[DEBUG]: Running config-se"]
[19.210741, "o", "t-passwords using lock (<FileLock using file '/var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_set_passwords'>)\r\n2022-08-25 19:51:15,660 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)\r\n2022-08-25 19:51:15,660 - util.py[DEBUG]: Read 3669 bytes from /etc/ssh/sshd_config\r\n2022-08-25 19:51:15,660 - ssh_util.py[DEBUG]: line 131: option PasswordAuthentication added with no\r\n2022-08-25 19:51:15,660 - util.py[DEBUG]: Writing to /etc/ssh/sshd_config - wb: [600] 3695 bytes\r\n2022-08-25 19:51:15,661 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh/sshd_config (recursive=False)\r\n2022-08-25 19:51:15,661 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh/sshd_config (recursive=False)\r\n2022-08-25 19:51:15,661 - subp.py[DEBUG]: Running command ['service', 'sshd', 'restart'] with allowed return codes [0] (shell=False, capture=True)\r\n2022-08-25 19:51:15,706 - cc_set_passwords.py[DEBUG]: Restarted the SSH daemon.\r\n2022-08-"]
[19.211323, "o", "25 19:51:15,707 - handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully\r\n2022-08-25 19:51:15,707 - stages.py[DEBUG]: Running module rh_subscription (<module 'cloudinit.config.cc_rh_subscription' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_rh_subscription.py'>) with frequency once-per-instance\r\n2022-08-25 19:51:15,707 - handlers.py[DEBUG]: start: modules-config/config-rh_subscription: running config-rh_subscription with frequency once-per-instance\r\n2022-08-25 19:51:15,707 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_rh_subscription - wb: [644] 24 bytes\r\n2022-08-25 19:51:15,708 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_rh_subscription (recursive=False)\r\n2022-08-25 19:51:15,709 - util.py[DEBUG]: Re"]
[19.211992, "o", "storing selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_rh_subscription (recursive=False)\r\n2022-08-25 19:51:15,710 - helpers.py[DEBUG]: Running config-rh_subscription using lock (<FileLock using file '/var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_rh_subscription'>)\r\n2022-08-25 19:51:15,710 - cc_rh_subscription.py[DEBUG]: rh_subscription: module not configured.\r\n2022-08-25 19:51:15,710 - handlers.py[DEBUG]: finish: modules-config/config-rh_subscription: SUCCESS: config-rh_subscription ran successfully\r\n2022-08-25 19:51:15,710 - stages.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_add_repo.py'>) with frequency once-per-instance\r\n2022-08-25 19:51:15,710 - handlers.py[DEBUG]: start: modules-config/config-yum-add-repo: running config-yu"]
[19.21266, "o", "m-add-repo with frequency once-per-instance\r\n2022-08-25 19:51:15,710 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_yum_add_repo - wb: [644] 25 bytes\r\n2022-08-25 19:51:15,711 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_yum_add_repo (recursive=False)\r\n2022-08-25 19:51:15,711 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_yum_add_repo (recursive=False)\r\n2022-08-25 19:51:15,712 - helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_yum_add_repo'>)\r\n2022-08-25 19:51:15,712 - cc_yum_add_repo.py["]
[19.213486, "o", "DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found\r\n2022-08-25 19:51:15,712 - handlers.py[DEBUG]: finish: modules-config/config-yum-add-repo: SUCCESS: config-yum-add-repo ran successfully\r\n2022-08-25 19:51:15,712 - stages.py[DEBUG]: Running module package-update-upgrade-install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_package_update_upgrade_install.py'>) with frequency once-per-instance\r\n2022-08-25 19:51:15,712 - handlers.py[DEBUG]: start: modules-config/config-package-update-upgrade-install: running config-package-update-upgrade-install with frequency once-per-instance\r\n2022-08-25 19:51:15,712 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_package_update_upgrade_install - wb: [644] 25 bytes\r\n2022-08-25 19:51:15,713 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.in"]
[19.214079, "o", "stance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_package_update_upgrade_install (recursive=False)\r\n2022-08-25 19:51:15,713 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_package_update_upgrade_install (recursive=False)\r\n2022-08-25 19:51:15,714 - helpers.py[DEBUG]: Running config-package-update-upgrade-install using lock (<FileLock using file '/var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/config_package_update_upgrade_install'>)\r\n2022-08-25 19:51:15,714 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/update_sources - wb: [644] 25 bytes\r\n2022-08-25 19:51:15,714 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-"]
[19.214853, "o", "1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/update_sources (recursive=False)\r\n2022-08-25 19:51:15,715 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/update_sources (recursive=False)\r\n2022-08-25 19:51:15,716 - helpers.py[DEBUG]: Running update-sources using lock (<FileLock using file '/var/lib/cloud/instances/ocid1.instance.oc1.ca-montreal-1.an4xkljrs3ocaxichrcbf5gq2almygrudoqnzpvr34s4bxgbiuwpg2s6pl6a/sem/update_sources'>)\r\n2022-08-25 19:51:15,718 - rhel.py[DEBUG]: Using DNF for package management\r\n2022-08-25 19:51:15,718 - subp.py[DEBUG]: Running command ['dnf', '-y', 'makecache'] with allowed return codes [0] (shell=False, capture=False)\r\n2022-08-25 19:51:25,582 - rhel.py[DEBUG]: Using DNF for package management\r\n2022-08-25 19:51:25,582 - subp.py[DEBUG]: Running command ['dnf', '-y', 'upgrade'] with allowed return codes [0] (shell=False, capture=False)\r\n\u001b]0;opc@amper"]
[19.215725, "o", "e-a1-almalinux-9-01:~\u0007\u001b[?2004h[opc@ampere-a1-almalinux-9-01 ~]$ "]
[21.154283, "o", "e"]
[21.358322, "o", "x"]
[21.481866, "o", "i"]
[21.546242, "o", "t"]
[21.946573, "o", "\r\n\u001b[?2004l\rlogout\r\n"]
[21.948196, "o", "Connection to 155.248.229.159 closed.\r\r\n"]
